### PR TITLE
fix (breadcumb): #51767- include the internal url only if exist

### PR DESCRIPTION
**Pull request by khalidbouhouch77**

### CODE REVIEW

**Comment by Bahlaouane-Hamza** [comment]
PHPcs failed

**Review by Bahlaouane-Hamza — CHANGES_REQUESTED** [review]
PHPcs failed

**Comment by khalidbouhouch77** [comment]
@Bahlaouane-Hamza 
The first argument of t() needs to be a literal string, which excludes:

- variables, even the parameters of a function: t($description)
- a concatenation of strings: t('If you want to add a link, click on' . '<a href="http://example.com">this link</a>.')
- the value returned from a function:t(get_menu_description())
- a constant: t(MYMODULE_MY_WIDGET_TITLE), t(MyClass::WIDGET_TITLE)

Ref : https://drupal.stackexchange.com/questions/9362/is-it-always-bad-to-pass-a-variable-through-t

**Comment by Bahlaouane-Hamza** [comment]
C'est pas lié à https://github.com/voidagency/vactory_starter_kit/blob/3.x/scripts/githooks/lint/InterfaceTranslationStandard/Sniffs/DisallowTranslationWithoutContextSniff.php ?

**Pull request merged**
